### ISSUE TITLE
fatal error: core_cm4.h: No such file or directory

### ISSUE THREAD

**Issue by trns1997** [Infineon/mtb-xmclib-cat3#1]
hey there,
I am using the xmclib from this repo without the modustoolbox. I came across that in the `CMSIS` folder the  `Core` headers files were missing. After adding the `Core` folder with all the necessary headers to the `CMSIS` folder (which i got from https://github.com/ARM-software/CMSIS_5/tree/3050b03d1bb8fba92ded34454e32fbf3aca3ff70/CMSIS), i was able to build with no issues. I was wondering if this was done on purpose or just it was just forgotten?

**Comment by vmedcy** [comment]
mtb-xmclib-cat3 is not "self-contained" library (unlike legacy XMCLib 2.X).

CMSIS-Core headers are provided as separate repo: https://github.com/Infineon/cmsis, currently based on https://github.com/ARM-software/CMSIS_5/tree/5.8.0
